2025-09-04 21:19:37,286 - uvicorn.error - INFO - Started server process [15772]
2025-09-04 21:19:37,287 - uvicorn.error - INFO - Waiting for application startup.
2025-09-04 21:19:37,288 - uvicorn.error - INFO - Application startup complete.
2025-09-04 21:19:37,290 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2025-09-04 21:24:38,056 - uvicorn.error - INFO - Shutting down
2025-09-04 21:24:38,163 - uvicorn.error - INFO - Waiting for application shutdown.
2025-09-04 21:24:38,164 - uvicorn.error - INFO - Application shutdown complete.
2025-09-04 21:24:38,165 - uvicorn.error - INFO - Finished server process [15772]
2025-09-04 21:24:50,627 - uvicorn.error - INFO - Started server process [7036]
2025-09-04 21:24:50,630 - uvicorn.error - INFO - Waiting for application startup.
2025-09-04 21:24:50,632 - uvicorn.error - INFO - Application startup complete.
2025-09-04 21:24:50,633 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2025-09-04 21:29:47,020 - uvicorn.error - INFO - Shutting down
2025-09-04 21:29:47,128 - uvicorn.error - INFO - Waiting for application shutdown.
2025-09-04 21:29:47,129 - uvicorn.error - INFO - Application shutdown complete.
2025-09-04 21:29:47,130 - uvicorn.error - INFO - Finished server process [7036]
2025-09-04 21:42:50,464 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at D:\conda\envs\py312\Lib\site-packages\uvicorn\server.py:69> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "D:\conda\envs\py312\Lib\site-packages\uvicorn\main.py", line 580, in run
    server.run()
  File "D:\conda\envs\py312\Lib\site-packages\uvicorn\server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code_softs\pycharm\PyCharm 2024.1.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code_softs\pycharm\PyCharm 2024.1.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
  File "D:\code_softs\pycharm\PyCharm 2024.1.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
  File "D:\conda\envs\py312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\conda\envs\py312\Lib\asyncio\tasks.py", line 396, in __wakeup
    self.__step()
  File "D:\code_softs\pycharm\PyCharm 2024.1.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 395, in step
    step_orig(task, exc)
  File "D:\conda\envs\py312\Lib\asyncio\tasks.py", line 303, in __step
    self.__step_run_and_handle_result(exc)
  File "D:\conda\envs\py312\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "D:\conda\envs\py312\Lib\site-packages\uvicorn\server.py", line 70, in serve
    with self.capture_signals():
         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\envs\py312\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "D:\conda\envs\py312\Lib\site-packages\uvicorn\server.py", line 331, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-09-04 22:11:57,628 - uvicorn.error - INFO - Started server process [9356]
2025-09-04 22:11:57,630 - uvicorn.error - INFO - Waiting for application startup.
2025-09-04 22:11:57,632 - uvicorn.error - INFO - Application startup complete.
2025-09-04 22:11:57,636 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
